name: "tag-and-release"
description: "
  analyse commit history and determine correct sem ver tag.
  on tag, create a github release.
  "

inputs:
  github-token:
    description: Github API Token
    required: true
  dry-run:
    description: Runs the tag and release action without creating a release
    default: "false"

outputs:
  new_release_published:
    description: "Whether a new release was published"
    value: ${{ steps.semantic.outputs.new_release_published }}
  new_release_version:
    description: "Version of the new release"
    value: ${{ steps.semantic.outputs.new_release_version }}
  new_release_major_version:
    description: "Major version of the new release"
    value: ${{ steps.semantic.outputs.new_release_major_version }}
  new_release_minor_version:
    description: "Minor version of the new release"
    value: ${{ steps.semantic.outputs.new_release_minor_version }}
  new_release_patch_version:
    description: "Patch version of the new release"
    value: ${{ steps.semantic.outputs.new_release_patch_version }}
  new_release_channel:
    description: "The distribution channel on which the last release was initially made available"
    value: ${{ steps.semantic.outputs.new_release_channel }}
  new_release_notes:
    description: "The release notes for the new release"
    value: ${{ steps.semantic.outputs.new_release_notes }}
  new_release_git_head:
    description: "The sha of the last commit being part of the new release"
    value: ${{ steps.semantic.outputs.new_release_git_head }}
  new_release_git_tag:
    description: "The Git tag associated with the new release"
    value: ${{ steps.semantic.outputs.new_release_git_tag }}
  last_release_version:
    description: "Version of the previous release, if there was one"
    value: ${{ steps.semantic.outputs.last_release_version }}
  last_release_git_head:
    description: "The sha of the last commit being part of the last release, if there was one"
    value: ${{ steps.semantic.outputs.last_release_git_head }}
  last_release_git_tag:
    description: "The Git tag associated with the last release, if there was one"
    value: ${{ steps.semantic.outputs.last_release_git_tag }}

runs:
  using: "composite"
  steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24

    - name: semantic release
      id: semantic
      uses: iwpnd/semantic-release-action@v1
      with:
        dry_run: ${{ inputs.dry-run == 'true'}}
        extra_plugins: |
          conventional-changelog-conventionalcommits
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
