name: test-release
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  tag-and-release:
    name: tag-and-release
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1
    permissions:
      id-token: write
      contents: write
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/commit-analyzer
            @semantic-release/github
            @semantic-release/release-notes-generator
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

